name: heed
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  get_it: ^6.0.0
  rxdart: ^0.26.0
  #  permission_handler: ^3.3.0
  data_connection_checker:
  flutter_inner_drawer:
  carousel_pro:
  datetime_picker_formfield: ^2.0.0
  dio: ^4.0.0
  flutter_html: ^1.3.0
  url_launcher: ^6.0.3
  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^9.0.0
  flutter_webview_plugin: ^0.3.11
  cupertino_icons: ^1.0.2
  zendesk: ^2.0.0
  firebase_messaging: ^9.1.0
  firebase_core: ^1.0.2
  firebase_crashlytics:
  firebase_analytics: ^7.1.1
#  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.7+1
  flutter_local_notifications: ^5.0.0+1

#  firebase_messaging: ^8.0.0-dev.15
#  firebase_core: ^0.7.0
#  firebase_crashlytics: ^0.4.0+1

  #  zendesk_plugin: ^1.2.1

  #  path_provider: ^2.0.1
  #  zendesk2: ^1.4.1

  #  zendesk:
  #  zendesk:
  #    git: git://github.com/emostar/flutter-zendesk
  #  firebase_messaging: ^7.0.3
#  firebase_messaging: ^9.1.0
  #  zendesk_plugin: ^1.2.1
  #  firebase_core: ^1.0.2
  #  firebase_crashlytics: ^1.0.0
#  firebase_core:
#  firebase_crashlytics:
#  firebase_analytics: ^7.1.1
#  flutter_local_notifications: ^0.8.4+3





dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter_launcher_icons: ^0.7.5
# flutter_launcher_icons: ^0.9.0
#flutter pub run flutter_launcher_icons:main
#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/images/app_icon.png"

#  flutter_native_splash: ^1.1.7+1

#flutter pub pub run flutter_native_splash:create
#flutter_native_splash:
#  image: assets/images/plain-white-background.jpg
#  color: "ffffff"
#  fill: true



#flutter pub run flutter_launcher_icons:main
#flutter_icons:
#  android: "launcher_icon"
#  ios: false
#  image_path: "assets/images/app_icon.png"

#  flutter_native_splash: ^0.1.9

#flutter pub pub run flutter_native_splash:create
#flutter_native_splash:
#  image: assets/images/plain-white-background.jpg
#  color: "ffffff"
#  fill: true





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/ar.json
    - assets/lang/en.json
    - assets/images/
    - assets/images/drawer_icons/
    - assets/images/mainIcons1X/
    - assets/images/1.55x/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: hk-grotesk
      fonts:
        - asset: assets/fonts/hk-grotesk.regular.ttf
          weight: 400
        - asset: assets/fonts/hk-grotesk.medium.ttf
          weight: 500
        - asset: assets/fonts/hk-grotesk.semibold.ttf
          weight: 600
        - asset: assets/fonts/hk-grotesk.bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

